language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
      env: DEPENDENCIES='low'
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - if [ "$DEPENDENCIES" != "low" ]; then composer update --ignore-platform-reqs; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --ignore-platform-reqs --prefer-lowest; fi;

script:
  - vendor/bin/phpspec run
  - vendor/bin/behat -f progress
